project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Raphael Morsomme"
  site-url: "https://rmorsomme.github.io/rmorsomme/"
  description: "Personal website of Raphael Morsomme"

  repo-url: https://github.com/rmorsomme/rmorsomme
  repo-actions: [edit, issue]

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2022, Raphael Morsomme"
    background: "#DFE1E9"

  navbar:
    background: "#DFE1E9"
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Academic research
      - href: teaching.qmd
        text: Teaching and mentoring
      - href: CV.qmd
        text: Curriculum vitae
#    right:
#      - icon: github
#        menu:
#          - text: Source Code
#            url:  https://github.com/rmorsomme/rmorsomme
#          - text: Report a Bug
#            url:  https://github.com/rmorsomme/rmorsomme


format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true
    link-external-newwindow: true

freeze: auto

editor: visual

