project:
  type: website
  output-dir: docs

website:
  search: false
  title: "Raphaël Morsomme"
  site-url: "https://rmorsomme.github.io/rmorsomme/"
  description: "Personal website of Raphaël Morsomme"

#  repo-url: https://github.com/rmorsomme/rmorsomme
#  repo-actions: [edit, issue]

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2022, Raphaël Morsomme"
    background: "#D96846"
    foreground: "#2F3020"  # '#596239'

  navbar:
    background: "#D96846"
    foreground: "#2F3020"
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
#      - href: teaching.qmd
#        text: Teaching and mentoring
      - href: documents/Curriculum Vitae - Raphaël Morsomme.pdf
        text: CV
    right:
      - icon: envelope
        href: mailto:raphael.morsomme@duke.edu
#    right:
#      - icon: github
#        menu:
#          - text: Source Code
#            url:  https://github.com/rmorsomme/rmorsomme
#          - text: Report a Bug
#            url:  https://github.com/rmorsomme/rmorsomme


format:
  html:
    #theme: [cosmo, theme.scss]
    #theme:
      #light: [cosmo, theme.scss]
      #dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    fontcolor: "#2F3020"
    toc: true
    link-external-newwindow: true
    backgroundcolor: "#CDCBD6"

freeze: auto

editor: visual

