---
#title: "Teaching and mentoring"
---

## Teaching statement

As an instructor, I see my role as taking students to the next step of their statistical education, whether it is an intermediate course in statistics, an undergraduate thesis, graduate studies in statistics or a statistics-related field, or simply become everyday critical consumers of statistical analyses. To accomplish this, the two principles that guide my approach to teaching are (1) to let students play an integral role in their statistical education, and (2) to make it easy for students to focus on learning statistics. During my Ph.D. program at Duke University, I have continuously developed my teaching skills through my enrollment in the [Certificate in College Teaching](https://gradschool.duke.edu/professional-development/programs/certificate-college-teaching/) and the course STA772 Mentoring Undergraduate STEM Research at the Department of Statistical Science in Fall 2021, and my participation in the [2022 summer course design workshop](https://sites.duke.edu/interdisciplinary/2021/11/02/new-opportunity-summer-course-development-grants/) organized by the Office of Interdisciplinary Studies.

My teaching of [STA101 Data Analysis and Statistical Inference](https://rmorsomme.github.io/website/) at Duke University in 2021 and 2022 illustrates this role and these two principles. Students enrolled in this course typically come from other departments and take it as an elective. Often, this is the only course in the field of statistics that they will ever take. My overarching goal was therefore for these students to become critical consumers of statistical analyses, both in their own academic field and in their everyday life. A concrete step that I took towards this goal was to replace the traditional midterm exam by a data analysis project. This midterm project, together with a second project at the end of the course, allowed students to gain direct experience with data analysis, and acquire the skills to recognize a sound and rigorous statistical analysis from a bogus one. To further develop their critical thinking, I had the students provide critical feedback on the data analysis projects of their peers. In addition, to expose students to the breadth of applications of statistical analysis, I frequently started lectures by watching and discussing [short videos](https://rmorsomme.github.io/website/slides/applications.html#/title-slide) illustrating the application of statistical analyses in various fields ranging from agriculture to car safety and house pricing.

To implement the first principle, I regularly gauged the students' attitude towards the course both informally through 1-minute micro-essays ("If any, what concept covered in the course do you not fully understand yet?", "What topic would like to learn more about?", etc) and formally through an anonymous midterm course evaluation in which I specifically ask for feedback as well as any suggestion to improve the course. The second principle guided the entire structure of the course, from the design of the lecture to the type of assignments or the choice of the textbook. I superseded lectures with in-class activities—in fact, I rarely talk for more than 15 minutes without having one such activity. These usually consist in multiple-choice and open-ended questions or in simple coding exercises and are done in groups or individually depending on what is most appropriate. These in-class activities are powerful tools for students to actively practice the skills and apply the concepts that they learned in class and, when combined with the micro-essays, to let me—the instructor—know of any gap in their knowledge. Moreover, to help students spend more time learning about statistics and less time looking for course material such as the lecture notes, the rubric for the projects, or the email address of the TA, I designed a user-friendly [course website](https://rmorsomme.github.io/website/) that plays the role of a one-stop shop with all the course material conveniently located in one place, helping students find any information they need quickly and seamlessly. Finally, I opted for the textbook [Introduction to Modern Statistics](https://openintro-ims.netlify.app/) from the OpenIntro project, a high quality textbook that is freely available online. Choosing a textbook that is freely available online was a concrete choice that helps students immediately focus on learning statistics rather than wait 2 weeks until they obtain a physical copy of the book.

## Certifications and training

-   [Certificate in College Teaching](https://gradschool.duke.edu/professional-development/programs/certificate-college-teaching/), Duke University (ongoing).
-   2021 – STA772 Mentoring Undergraduate STEM Research, Duke University.

## Instructor of record

-   Summer 2021 – STA101 Data Analysis and Statistical Inference, Duke University
-   [Summer 2022 – STA101 Data Analysis and Statistical Inference, Duke University](https://rmorsomme.github.io/website/)

## Teaching assistant

-   2024 – STA863 Advanced Statistical Computing (Ph.D.), Duke University.
-   2023 – STA561 Probabilistic Machine Learning (masters), Duke University.
-   2022 – STA310 Generalized linear models (undergraduate), Duke University.
-   2021 – STA732 Case studies (Ph.D.), Duke University.
-   2020 – STA540 Case studies (masters), Duke University.
-   2019 – STA440 Case studies (undergraduate), Duke University.
-   2017 – STA101 Introduction to Statistical Science, University College Freiburg.

## Workshop

-   2018-2022 – Introduction to `R`, University College Maastricht ([slides](/documents/Intro%20to%20R.html)).

## Tutoring and mentoring

-   2021-present – Academic mentor of M. Chen (Masters in statistical science).
-   2020-present – Private tutoring.
-   2024 – Research mentor for the Intro to Undergrad Research in Statistical Science Workshop, Duke University.
-   2023-2024 – Research mentor for the Thesis Writer's Mentoring Workshop, Duke University.
-   2021-2024 – Academic tutor, SPIRE Fellows Program, Duke University.
-   2021-2023 – Academic mentor of J. Huang (major in statistical science and computer science), recipient of the Faculty Scholars Award for Excellence in Research, the highest distinction offered by Duke University for undergraduate research.
-   2020-2021 – Research mentor, Lumiere Research Scholar Program.

## Awards and grants

-   2022 – Outstanding Mentor of Undergraduate Research Award, Duke University.
-   2022 – [Summer Course Design Grant](https://interdisciplinary.duke.edu/opportunities/summer-course-development-grants/), Duke University.
